### ISSUE TITLE
Filenames when comparing

### ISSUE THREAD

**Issue by gudmundurste12** [ThrosturX/rl-mouse#2]
When running the command

python teal.py ex2_gudmundurste12.py --compare_to ex2_gudmundurste12_copy.py --grid_size 8 --seed 2608922589

the first test ran well, but when the second test was supposed to run, I got this: 

ERROR
traceback:
Traceback (most recent call last):
  File "teal.py", line 216, in <module>
    comparison()
  File "teal.py", line 30, in comparison
    e2 = count_epochs(args.compare_to)
  File "teal.py", line 60, in count_epochs
    exercise = **import**(convert(name))
ImportError: No module named ex2_gudmundurste12_co
None
message:
No module named ex2_gudmundurste12_co

Then I tried different names for the file:
ex2_gudmundurste12_cooooooooopy.py returned
No module named ex2_gudmundurste12_cooooooooo

and ex2_gudmpyundurste12_copy.py returned
No module named ex2_gudmpyundurste12_co

Could this be an off-by-one error when parsing the filename?

**Comment by gudmundurste12** [comment]
Also, comparing worked without error when the file was renamed to ex2_gudmundurste12_2.py

**Comment by ThrosturX** [comment]
Fixed, it seems to be a weird but with `str.rstrip(pattern)` ignoring the period in `.py`.
